branch-defaults:
  default:
    environment: Demo666-env
    group_suffix: null
global:
  application_name: demo666
  default_region: ap-southeast-2
  profile: null
  platform_name: PHP
  platform_version: 8.4.al2023
  workspace_type: Application
